export default function Head() {
  return (
    <>
      <title>Create Next App</title>
      <meta name='description' content='Generated by create next app' />
      <meta name='viewport' content='initial-scale=1, width=device-width' />
      <link rel='icon' href='/favicon.ico' />
      <link
        rel='stylesheet'
        href='https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap'
        precedence='default'
      />
      <link
        rel='stylesheet'
        href='https://fonts.googleapis.com/icon?family=Material+Icons'
        precedence='default'
      />
    </>
  );
}
